/**
 * Golden expected outputs (Myanmar Unicode, storage order per UTN #11).
 * Every string here is validated by `validateMyanmarOrthography` in tests and
 * by `pnpm validate:dictionary`; spellings follow the most common real-world
 * form of each name part.
 */
import { EXTENDED_GOLDEN_SYLLABLES } from "./extended-syllables";

export const GOLDEN: Record<string, string> = {
  "Mg Mg": "မောင်မောင်",
  "Maung Maung": "မောင်မောင်",
  "Aung Kyaw": "အောင်ကျော်",
  "U Thant": "ဦးသန့်",
  "Ko Ko": "ကိုကို",
  "Kyaw Min": "ကျော်မင်း",
  "Daw Khin Myo": "ဒေါ်ခင်မျိုး",
  "Htoo Aung Ye Yint": "ထူးအောင်ရဲရင့်",
  "Thant Zin": "သန့်ဇင်",
  "Zaw Min": "ဇော်မင်း",
  "Nay Phone": "နေဖုန်း",
  "Pyae Sone": "ပြည့်စုံ",
  "Shwe Yee": "ရွှေရည်",
  "Hnin Wai": "နှင်းဝေ",
  "Wai Yan": "ဝေယံ",
  "Chan Myae": "ချမ်းမြေ့",
  "Ngwe Tin": "ငွေတင်",
  Sandar: "စန္ဒာ",
  Thidar: "သီတာ",
  "Moe Moe": "မိုးမိုး",
  "Aung San Suu Kyi": "အောင်ဆန်းစုကြည်",
  "Min Aung": "မင်းအောင်",
  "Su Su": "စုစု",
  Nilar: "နီလာ",
  "Zaw Min Htet": "ဇော်မင်းထက်",
  "Kyaw Zin Win": "ကျော်ဇင်ဝင်း",
  "Phyo Thiha": "ဖြိုးသီဟ",
  "Myat Noe": "မြတ်နိုး",
  "Ei Ei": "အိအိ",
  "Khin Khin": "ခင်ခင်",
  "Hein Htet": "ဟိန်းထက်",
  "Nay Lin": "နေလင်း",
  "Thu Rein": "သူရိန်",
  Yadanar: "ရတနာ",
  "Htet Htet": "ထက်ထက်",
  "Mya Mya": "မြမြ",
  Thiri: "သီရိ",
  "Win Win": "ဝင်းဝင်း",
  "Myo Min": "မျိုးမင်း",
  "Hla Hla": "လှလှ",
  "Myint Myint": "မြင့်မြင့်",
  "Chit Su": "ချစ်စု",
  "Khin Mar": "ခင်မာ",
  "Saw Mya": "စောမြ",
  "Naw Htoo": "နော်ထူး",
  "Sai Hlaing": "စိုင်းလှိုင်",
  "Nang Hla": "နန်းလှ",
  "Dr Aung": "ဒေါက်တာအောင်",
  "Ma Thida": "မသီတာ",
  Ma: "မ",
  "Sai Kyaw": "စိုင်းကျော်",
  "Nay Win": "နေဝင်း",
  "Kyaw Swa": "ကျော်စွာ",
  "Tin Win": "တင်ဝင်း",
  "Hla Myint": "လှမြင့်",
  "U Nu": "ဦးနု",
  "Aung San": "အောင်ဆန်း",
  "Khin Nyunt": "ခင်ညွန့်",
  "Tin Oo": "တင်ဦး",
  "Myint Oo": "မြင့်ဦး",
  "Win Htet": "ဝင်းထက်",
  "Lin Htet": "လင်းထက်",
  "Phone Myat": "ဖုန်းမြတ်",
  "Shwe Tun": "ရွှေထွန်း",
  "Nyein Lin": "ငြိမ်းလင်း",
  "Phyo Wai": "ဖြိုးဝေ",
  "Hnin Ei": "နှင်းအိ",
  "Chan Thar": "ချမ်းသာ",
  "Ngwe Oo": "ငွေဦး",
  "Sandar Win": "စန္ဒာဝင်း",
  "Thidar Aung": "သီတာအောင်",
  "Moe Kyi": "မိုးကြည်",
  "Htet Aung": "ထက်အောင်",
  "Thiri Myat": "သီရိမြတ်",
  "Yadanar Oo": "ရတနာဦး",
  "Nanda Win": "နန္ဒာဝင်း",
  "Kaung Myat": "ကောင်းမြတ်",
  "Soe Moe": "စိုးမိုး",
  "Khaing Myo": "ခိုင်မျိုး",
  "Paing Thu": "ပိုင်သူ",
  "Wint Yee": "ဝင့်ရည်",
  "Ei Mon": "အိမွန်",
  "May Kyi": "မေကြည်",
  "Thi Ha": "သီဟ",
  "Bo Bo": "ဗိုလ်ဗိုလ်",
  "Mon Mon": "မွန်မွန်",
  "Zin Mar": "ဇင်မာ",
  "Ma Hla": "မလှ",
  "Hein Ko": "ဟိန်းကို",
  "Zaw Htet": "ဇော်ထက်",
  "Kyaw Swa Win": "ကျော်စွာဝင်း",
  "Min Zaw Htet": "မင်းဇော်ထက်",
  "Aung Ko": "အောင်ကို",
  "Sai Aung": "စိုင်းအောင်",
  "Nay Phone Kyi": "နေဖုန်းကြည်",
  "Mya Thu": "မြသူ",
  "Thu Ya": "သူရ",
  "Thuya": "သူရ",
  "Ni Ni": "နီနီ",
  "Sein Shwe": "စိန်ရွှေ",
  "Tint Tint": "တင့်တင့်",
  "Kyaw Lin Htet": "ကျော်လင်းထက်",
  "Daw Khin Mar": "ဒေါ်ခင်မာ",
  "U Win": "ဦးဝင်း",
  "Mg Ba": "မောင်ဘ",
  "Ba Tin": "ဘတင်",
};

/** Canonical romanized syllable -> top Myanmar spelling (must be a dictionary hit). */
const CORE_GOLDEN_SYLLABLES: Record<string, string> = {
  Mg: "မောင်",
  Maung: "မောင်",
  U: "ဦး",
  Daw: "ဒေါ်",
  Ko: "ကို",
  Ma: "မ",
  Saw: "စော",
  Naw: "နော်",
  Sai: "စိုင်း",
  Nang: "နန်း",
  Dr: "ဒေါက်တာ",
  Aung: "အောင်",
  Kyaw: "ကျော်",
  Min: "မင်း",
  Myo: "မျိုး",
  Khin: "ခင်",
  Htoo: "ထူး",
  Ye: "ရဲ",
  Yint: "ရင့်",
  Thant: "သန့်",
  Zin: "ဇင်",
  Zaw: "ဇော်",
  Phone: "ဖုန်း",
  Sone: "စုံ",
  Pyae: "ပြည့်",
  Shwe: "ရွှေ",
  Yee: "ရည်",
  Hnin: "နှင်း",
  Wai: "ဝေ",
  Yan: "ယံ",
  Chan: "ချမ်း",
  Myae: "မြေ့",
  Ngwe: "ငွေ",
  Tin: "တင်",
  Moe: "မိုး",
  Nay: "နေ",
  Htet: "ထက်",
  Naing: "နိုင်",
  Lwin: "လွင်",
  Oo: "ဦး",
  Phyo: "ဖြိုး",
  Nyein: "ငြိမ်း",
  Su: "စု",
  Suu: "စု",
  Hlaing: "လှိုင်",
  Thu: "သူ",
  Thuya: "သူရ",
  Ya: "ရ",
  Ba: "ဘ",
  Win: "ဝင်း",
  Soe: "စိုး",
  Mya: "မြ",
  Aye: "အေး",
  Khaing: "ခိုင်",
  Thet: "သက်",
  Paing: "ပိုင်",
  Wint: "ဝင့်",
  Ei: "အိ",
  May: "မေ",
  Kaung: "ကောင်း",
  Myat: "မြတ်",
  Hein: "ဟိန်း",
  Myint: "မြင့်",
  Htun: "ထွန်း",
  Tun: "ထွန်း",
  Khant: "ခန့်",
  Lin: "လင်း",
  Han: "ဟန်",
  Hla: "လှ",
  Chit: "ချစ်",
  Mar: "မာ",
  Lar: "လာ",
  Tar: "တာ",
  Dar: "ဒါ",
  Zar: "ဇာ",
  Phyu: "ဖြူ",
  Bo: "ဗိုလ်",
  Mon: "မွန်",
  Yin: "ယဉ်",
  Noe: "နိုး",
  Htay: "ထေး",
  Htar: "ထား",
  Kha: "ခ",
  Swa: "စွာ",
  Gyi: "ကြီး",
  Htwe: "ထွေး",
  Zu: "ဇူ",
  San: "ဆန်း",
  Yu: "ယု",
  Thi: "သီ",
  Ha: "ဟ",
  Rein: "ရိန်",
  Kyi: "ကြည်",
  Nyi: "ညီ",
  Nyunt: "ညွန့်",
  Khine: "ခိုင်",
  Thein: "သိန်း",
  Than: "သန်း",
  Maw: "မော်",
  Lay: "လေး",
  Ni: "နီ",
  Pyone: "ပြုံး",
  Tint: "တင့်",
  Toe: "တိုး",
  Kyal: "ကြယ်",
  Cho: "ချို",
  Sein: "စိန်",
  Nwe: "နွယ်",
  Ohn: "အုန်း",
  Nu: "နု",
  Thin: "သင်း",
  Thaw: "သော်",
  Zun: "ဇွန်",
  Nway: "နွေး",
  Myaing: "မြိုင်",
  Pwint: "ပွင့်",
  War: "ဝါ",
  Latt: "လတ်",
  La: "လ",
  Nge: "ငယ်",
  Hsu: "ဆု",
  Htike: "ထိုက်",
  Naung: "နောင်",
  Hmue: "မှူး",
  Lu: "လူ",
  Thit: "သစ်",
  Ein: "အိမ်",
  Tha: "သာ",
  Myit: "မြစ်",
  Kay: "ကေ",
  Mi: "မိ",
  Wa: "ဝ",
  Nyo: "ညို",
  Shein: "ရှိန်",
  Wutt: "ဝတ်",
  Pann: "ပန်း",
  Swe: "ဆွေ",
  Sin: "စင်",
  Si: "ဆီ",
  Yadanar: "ရတနာ",
  Sandar: "စန္ဒာ",
  Thidar: "သီတာ",
  Nilar: "နီလာ",
  Thiri: "သီရိ",
  Thiha: "သီဟ",
  Thura: "သူရ",
  Thazin: "သဇင်",
  Zayar: "ဇေယျာ",
  Zarni: "ဇာနည်",
  Eaindra: "အိန္ဒြာ",
  Thuzar: "သူဇာ",
  Nanda: "နန္ဒာ",
  Sithu: "စည်သူ",
  Thandar: "သန္တာ",
  Zinmar: "ဇင်မာ",
  Marlar: "မာလာ",
  Thinzar: "သင်ဇာ",
  Sabai: "စံပယ်",
  Padonmar: "ပဒုမ္မာ",
  Mingalar: "မင်္ဂလာ",
  Kalyar: "ကလျာ",
  Thitsar: "သစ္စာ",
};

/** Core curated entries win over extended rule-generated syllables on key collision. */
export const GOLDEN_SYLLABLES: Record<string, string> = {
  ...EXTENDED_GOLDEN_SYLLABLES,
  ...CORE_GOLDEN_SYLLABLES,
};

/** Secondary spellings offered as alternatives (weight 0.85). */
export const ALTERNATE_SPELLINGS: Record<string, string> = {
  Min: "မင်",
  Yint: "ယဉ့်",
  Wai: "ဝဲ",
  Yan: "ရန်",
  Myae: "မြဲ",
  Tun: "တွန်း",
  Win: "ဝင်",
  Lin: "လင်",
  Myo: "မြို့",
  Thet: "ထက်",
  Htet: "သက်",
  Nanda: "နန္ဒ",
  Mon: "မုံ",
  San: "စန်း",
  Su: "ဆု",
  Si: "စီ",
  Sin: "ဆင်",
  Ya: "ယ",
  Ba: "ဗ",
};

export const ROMAN_VARIANTS: Record<string, string[]> = {
  mg: ["mg", "m.g.", "m g"],
  maung: ["maung"],
  u: ["u", "uu"],
  oo: ["oo"],
  daw: ["daw", "daw."],
  dr: ["dr", "dr."],
  nang: ["nang", "nan"],
  kyaw: ["kyaw", "gyaw", "kyaw."],
  aung: ["aung", "oung"],
  pyae: ["pyae", "pyay"],
  htoo: ["htoo", "htu"],
  ye: ["ye", "yay"],
  yint: ["yint"],
  myo: ["myo", "myoh"],
  myint: ["myint", "mint"],
  min: ["min", "minn"],
  win: ["win", "winn", "wyn"],
  lin: ["lin", "linn"],
  zin: ["zin", "zinn"],
  thin: ["thin", "thinn"],
  phone: ["phone", "phon"],
  yee: ["yee", "yi"],
  wai: ["wai", "way"],
  moe: ["moe", "mo"],
  soe: ["soe", "so"],
  sandar: ["sandar", "sanda"],
  thidar: ["thidar", "thida"],
  nilar: ["nilar", "nila"],
  yadanar: ["yadanar", "yadana"],
  zayar: ["zayar", "zeyar", "zeya"],
  eaindra: ["eaindra", "eindra"],
  nanda: ["nanda", "nandar"],
  thandar: ["thandar", "thanda"],
  marlar: ["marlar", "marla"],
  htun: ["htun", "htoon"],
  su: ["su", "suu"],
  aye: ["aye", "ay"],
  myae: ["myae", "myay"],
  htet: ["htet", "htett"],
  thet: ["thet", "thett"],
  myat: ["myat", "myatt"],
  latt: ["latt", "lat"],
  wutt: ["wutt", "wut"],
  pann: ["pann", "pan"],
  kyi: ["kyi", "kyee"],
  tha: ["tha", "thar"],
  hsu: ["hsu", "hsuu"],
  khine: ["khine"],
  nway: ["nway"],
  shwe: ["shwe", "shway"],
};

export const TITLE_KEYS = new Set(["Mg", "Maung", "U", "Daw", "Ko", "Ma", "Saw", "Naw", "Sai", "Nang", "Dr"]);

export const RESERVED_ROMAN = new Set(
  Object.keys(GOLDEN_SYLLABLES).flatMap((key) => {
    const lower = key.toLowerCase();
    const extras = ROMAN_VARIANTS[lower] ?? [lower];
    return extras.map((v) => v.toLowerCase());
  }),
);
